create extension if not exists pgcrypto;

create schema if not exists flowa;

do $$
begin
  create type flowa.os_family as enum (
    'ios',
    'android',
    'windows',
    'macos',
    'linux',
    'unknown'
  );
exception
  when duplicate_object then null;
end;
$$;

do $$
begin
  create type flowa.membership_role as enum (
    'owner',
    'admin',
    'moderator'
  );
exception
  when duplicate_object then null;
end;
$$;

do $$
begin
  create type flowa.membership_status as enum (
    'invited',
    'active',
    'disabled'
  );
exception
  when duplicate_object then null;
end;
$$;

do $$
begin
  create type flowa.session_status as enum (
    'draft',
    'active',
    'completed'
  );
exception
  when duplicate_object then null;
end;
$$;

do $$
begin
  create type flowa.age_mode as enum (
    'fixed',
    'variable'
  );
exception
  when duplicate_object then null;
end;
$$;

create table if not exists flowa.profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email text not null unique,
  display_name text,
  default_organization_id uuid,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint flowa_profiles_email_check check (position('@' in email) > 1)
);

create table if not exists flowa.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  created_by uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists flowa.memberships (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references flowa.organizations (id) on delete cascade,
  user_id uuid references auth.users (id) on delete set null,
  invited_email text not null,
  role flowa.membership_role not null default 'moderator',
  status flowa.membership_status not null default 'invited',
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint flowa_memberships_email_check check (position('@' in invited_email) > 1),
  constraint flowa_memberships_org_email_unique unique (organization_id, invited_email)
);

create table if not exists flowa.sessions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references flowa.organizations (id) on delete cascade,
  slug text not null unique,
  name text not null,
  description text not null default '',
  screen_time_limit_minutes integer not null default 60 check (screen_time_limit_minutes between 1 and 1440),
  age_mode flowa.age_mode not null default 'variable',
  fixed_age integer,
  status flowa.session_status not null default 'active',
  created_by uuid not null references auth.users (id) on delete cascade,
  starts_at timestamptz not null default timezone('utc', now()),
  ends_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint flowa_sessions_fixed_age_check check (
    (age_mode = 'fixed' and fixed_age between 1 and 120)
    or (age_mode = 'variable' and fixed_age is null)
  )
);

create table if not exists flowa.session_collaborators (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references flowa.sessions (id) on delete cascade,
  membership_id uuid not null references flowa.memberships (id) on delete cascade,
  role flowa.membership_role not null default 'moderator',
  created_at timestamptz not null default timezone('utc', now()),
  constraint flowa_session_collaborators_unique unique (session_id, membership_id)
);

create table if not exists flowa.session_submissions (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references flowa.sessions (id) on delete cascade,
  participant_key uuid not null,
  age integer not null check (age between 1 and 120),
  screen_time_minutes integer not null check (screen_time_minutes between 0 and 1440),
  detected_os flowa.os_family not null default 'unknown',
  ip_address inet,
  user_agent text,
  submitted_at timestamptz not null default timezone('utc', now()),
  entry_date date not null default (timezone('utc', now())::date)
);

create table if not exists flowa.activity_log (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references flowa.organizations (id) on delete cascade,
  session_id uuid references flowa.sessions (id) on delete set null,
  actor_user_id uuid references auth.users (id) on delete set null,
  activity_type text not null,
  title text not null,
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists flowa_memberships_user_idx
  on flowa.memberships (user_id, status);

create index if not exists flowa_memberships_org_idx
  on flowa.memberships (organization_id, status);

create index if not exists flowa_sessions_org_idx
  on flowa.sessions (organization_id, created_at desc);

create index if not exists flowa_sessions_status_idx
  on flowa.sessions (status, starts_at desc);

create index if not exists flowa_session_submissions_session_idx
  on flowa.session_submissions (session_id, submitted_at desc);

create index if not exists flowa_session_submissions_participant_idx
  on flowa.session_submissions (session_id, participant_key, submitted_at desc);

create index if not exists flowa_session_submissions_entry_date_idx
  on flowa.session_submissions (entry_date desc);

create index if not exists flowa_session_submissions_os_idx
  on flowa.session_submissions (detected_os, submitted_at desc);

create index if not exists flowa_activity_log_org_idx
  on flowa.activity_log (organization_id, created_at desc);

create or replace function flowa.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists user_profiles_set_updated_at on screentime.user_profiles;
create trigger user_profiles_set_updated_at
before update on screentime.user_profiles
for each row
execute function screentime.set_updated_at();

drop trigger if exists organizations_set_updated_at on screentime.organizations;
create trigger organizations_set_updated_at
before update on screentime.organizations
for each row
execute function screentime.set_updated_at();

drop trigger if exists organization_memberships_set_updated_at on screentime.organization_memberships;
create trigger organization_memberships_set_updated_at
before update on screentime.organization_memberships
for each row
execute function screentime.set_updated_at();

drop trigger if exists tracked_sessions_set_updated_at on screentime.tracked_sessions;
create trigger tracked_sessions_set_updated_at
before update on screentime.tracked_sessions
for each row
execute function screentime.set_updated_at();

drop trigger if exists flowa_profiles_set_updated_at on flowa.profiles;
create trigger flowa_profiles_set_updated_at
before update on flowa.profiles
for each row
execute function flowa.set_updated_at();

drop trigger if exists flowa_organizations_set_updated_at on flowa.organizations;
create trigger flowa_organizations_set_updated_at
before update on flowa.organizations
for each row
execute function flowa.set_updated_at();

drop trigger if exists flowa_memberships_set_updated_at on flowa.memberships;
create trigger flowa_memberships_set_updated_at
before update on flowa.memberships
for each row
execute function flowa.set_updated_at();

drop trigger if exists flowa_sessions_set_updated_at on flowa.sessions;
create trigger flowa_sessions_set_updated_at
before update on flowa.sessions
for each row
execute function flowa.set_updated_at();

create or replace view flowa.latest_session_participants as
select distinct on (session_id, participant_key)
  id,
  tracked_session_id,
  session_id,
  participant_key,
  age,
  screen_time_minutes,
  detected_os,
  ip_address,
  user_agent,
  submitted_at,
  entry_date
from flowa.session_submissions
order by session_id, participant_key, submitted_at desc;

create or replace view flowa.session_age_statistics as
select
  session_id,
  case
    when age < 25 then '18-24'
    when age < 35 then '25-34'
    when age < 45 then '35-44'
    when age < 55 then '45-54'
    else '55+'
  end as age_bucket,
  count(*)::integer as participants,
  round(avg(screen_time_minutes)::numeric, 1) as average_minutes,
  max(screen_time_minutes)::integer as maximum_minutes
from flowa.latest_session_participants
group by session_id, 2;

create or replace view flowa.session_overview as
select
  sessions.id as session_id,
  sessions.organization_id,
  sessions.slug,
  sessions.name,
  sessions.status,
  sessions.screen_time_limit_minutes,
  sessions.created_at,
  sessions.starts_at,
  sessions.ends_at,
  count(participants.id)::integer as participant_count,
  round(avg(participants.screen_time_minutes)::numeric, 1) as average_minutes,
  max(participants.screen_time_minutes)::integer as maximum_minutes,
  max(participants.submitted_at) as latest_submission_at
from flowa.sessions as sessions
left join flowa.latest_session_participants as participants
  on participants.session_id = sessions.id
group by
  sessions.id,
  sessions.organization_id,
  sessions.slug,
  sessions.name,
  sessions.status,
  sessions.screen_time_limit_minutes,
  sessions.created_at,
  sessions.starts_at,
  sessions.ends_at;

grant usage on schema flowa to authenticated, service_role;
grant select on flowa.profiles, flowa.memberships, flowa.organizations, flowa.sessions to authenticated, service_role;
grant select, insert, update, delete on all tables in schema flowa to service_role;
grant usage on all sequences in schema flowa to service_role;
grant select on flowa.latest_session_participants, flowa.session_age_statistics, flowa.session_overview to authenticated, service_role;
grant execute on function flowa.set_updated_at() to service_role;

alter table flowa.profiles enable row level security;
alter table flowa.organizations enable row level security;
alter table flowa.memberships enable row level security;
alter table flowa.sessions enable row level security;
alter table flowa.session_collaborators enable row level security;
alter table flowa.session_submissions enable row level security;
alter table flowa.activity_log enable row level security;

drop policy if exists flowa_profiles_self_select on flowa.profiles;
create policy flowa_profiles_self_select
on flowa.profiles
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists flowa_profiles_self_update on flowa.profiles;
create policy flowa_profiles_self_update
on flowa.profiles
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists flowa_memberships_self_select on flowa.memberships;
create policy flowa_memberships_self_select
on flowa.memberships
for select
to authenticated
using (
  auth.uid() = user_id
  or lower(coalesce(auth.jwt() ->> 'email', '')) = lower(invited_email)
);

drop policy if exists flowa_organizations_member_select on flowa.organizations;
create policy flowa_organizations_member_select
on flowa.organizations
for select
to authenticated
using (
  exists (
    select 1
    from flowa.memberships
    where memberships.organization_id = organizations.id
      and memberships.status = 'active'
      and memberships.user_id = auth.uid()
  )
);

drop policy if exists flowa_sessions_member_select on flowa.sessions;
create policy flowa_sessions_member_select
on flowa.sessions
for select
to authenticated
using (
  exists (
    select 1
    from flowa.memberships
    where memberships.organization_id = sessions.organization_id
      and memberships.status = 'active'
      and memberships.user_id = auth.uid()
  )
);