create extension if not exists pgcrypto;

create schema if not exists screentime;

create type screentime.os_family as enum (
  'ios',
  'android',
  'windows',
  'macos',
  'linux',
  'unknown'
);

create type screentime.admin_role as enum (
  'owner',
  'admin'
);

create type screentime.admin_status as enum (
  'invited',
  'active',
  'disabled'
);

create table if not exists screentime.screen_time_entries (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null,
  screen_time_minutes integer not null check (screen_time_minutes between 0 and 1440),
  detected_os screentime.os_family not null default 'unknown',
  ip_address inet,
  user_agent text,
  submitted_at timestamptz not null default timezone('utc', now()),
  entry_date date not null default (timezone('utc', now())::date)
);

create index if not exists screen_time_entries_session_idx
  on screentime.screen_time_entries (session_id, submitted_at desc);

create index if not exists screen_time_entries_os_idx
  on screentime.screen_time_entries (detected_os, submitted_at desc);

create index if not exists screen_time_entries_entry_date_idx
  on screentime.screen_time_entries (entry_date desc);

create index if not exists screen_time_entries_ip_idx
  on screentime.screen_time_entries (ip_address);

create table if not exists screentime.admin_profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email text not null unique,
  role screentime.admin_role not null default 'admin',
  status screentime.admin_status not null default 'invited',
  invited_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint admin_profiles_email_check check (position('@' in email) > 1)
);

create table if not exists screentime.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users (id) on delete set null,
  action text not null,
  target_email text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create or replace function screentime.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists admin_profiles_set_updated_at on screentime.admin_profiles;

create trigger admin_profiles_set_updated_at
before update on screentime.admin_profiles
for each row
execute function screentime.set_updated_at();

create or replace function screentime.is_admin(check_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = screentime, auth, public
as $$
  select exists (
    select 1
    from screentime.admin_profiles
    where user_id = check_user_id
      and status = 'active'
  );
$$;

create or replace function screentime.bootstrap_admin(
  target_email text,
  target_role screentime.admin_role default 'owner'
)
returns uuid
language plpgsql
security definer
set search_path = screentime, auth, public
as $$
declare
  auth_user_id uuid;
begin
  select id
  into auth_user_id
  from auth.users
  where lower(email) = lower(target_email)
  order by created_at desc
  limit 1;

  if auth_user_id is null then
    raise exception 'Auth user with email % does not exist. Create it in Supabase Auth first.', target_email;
  end if;

  insert into screentime.admin_profiles (user_id, email, role, status)
  values (auth_user_id, lower(target_email), target_role, 'active')
  on conflict (user_id) do update
    set email = excluded.email,
        role = excluded.role,
        status = 'active',
        updated_at = timezone('utc', now());

  insert into screentime.admin_audit_log (actor_user_id, action, target_email, metadata)
  values (
    auth_user_id,
    'bootstrap_admin',
    lower(target_email),
    jsonb_build_object('role', target_role)
  );

  return auth_user_id;
end;
$$;

create or replace view screentime.latest_session_entries as
select distinct on (session_id)
  id,
  session_id,
  screen_time_minutes,
  detected_os,
  ip_address,
  user_agent,
  submitted_at,
  entry_date
from screentime.screen_time_entries
order by session_id, submitted_at desc;

create or replace view screentime.os_statistics as
select
  detected_os,
  count(*)::integer as participants,
  round(avg(screen_time_minutes)::numeric, 1) as average_minutes,
  min(screen_time_minutes)::integer as minimum_minutes,
  max(screen_time_minutes)::integer as maximum_minutes
from screentime.latest_session_entries
group by detected_os;

create or replace view screentime.ip_statistics as
select
  coalesce(host(ip_address), 'unknown') as ip_address,
  count(*)::integer as submissions,
  max(submitted_at) as last_seen,
  round(avg(screen_time_minutes)::numeric, 1) as average_minutes
from screentime.screen_time_entries
group by coalesce(host(ip_address), 'unknown');

grant usage on schema screentime to anon, authenticated, service_role;
grant select on screentime.admin_profiles to authenticated, service_role;
grant select, insert, update, delete on all tables in schema screentime to service_role;
grant usage on all sequences in schema screentime to service_role;
grant select on screentime.latest_session_entries, screentime.os_statistics, screentime.ip_statistics to service_role;
grant execute on function screentime.is_admin(uuid) to authenticated, service_role;
grant execute on function screentime.bootstrap_admin(text, screentime.admin_role) to service_role;

alter table screentime.screen_time_entries enable row level security;
alter table screentime.admin_profiles enable row level security;
alter table screentime.admin_audit_log enable row level security;

drop policy if exists admin_profiles_self_select on screentime.admin_profiles;
create policy admin_profiles_self_select
on screentime.admin_profiles
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists admin_profiles_self_update on screentime.admin_profiles;
create policy admin_profiles_self_update
on screentime.admin_profiles
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);